package router

import (
	common "gin-myboot/modules/common/router"
	generator "gin-myboot/modules/generator/router"
	install "gin-myboot/modules/install/router"
	storage "gin-myboot/modules/storage/router"
	system "gin-myboot/modules/system/router"
	"github.com/gin-gonic/gin"
	// Code generated import package Begin; DO NOT EDIT.
	article "gin-myboot/modules/article/router"
	// Code generated import package End; DO NOT EDIT.
)

type RouterGroup struct {
}

var RouterGroupApp = new(RouterGroup)

func (s *RouterGroup) Init(Router *gin.RouterGroup) {

	Group := Router.Group("api")

	// Router.Use(middleware.JWTAuth()).Use(middleware.CasbinHandler()) // 开启权限

	common.InitCommonRouter(Group)
	system.InitSystemRouter(Group)
	storage.InitStorageRouter(Group)
	generator.InitAutoCodeRouter(Group) // 创建自动化代码
	install.InitInstallRouter(Group) // 系统安装配置
	// Code generated by gin-myboot Begin; DO NOT EDIT.
	article.InitSysArticleRouter(Group)
	// Code generated by gin-myboot End; DO NOT EDIT.
}
