package initialize

import (
	"gin-myboot/global"
	"gin-myboot/initialize/internal"
	generator "gin-myboot/modules/generator/model"
	storage "gin-myboot/modules/storage/model"
	system "gin-myboot/modules/system/model"
	"os"

	"go.uber.org/zap"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
	// Code generated import package Begin; DO NOT EDIT.
	article "gin-myboot/modules/article/model"
	// Code generated import package End; DO NOT EDIT.
)

// Gorm
// @author: SliverHorn
// @function: Gorm
// @description: 初始化数据库并产生数据库全局变量
// @return: *gorm.DB
func Gorm() *gorm.DB {
	switch global.Config.System.DbType {
	case "mysql":
		return GormMysql()
	default:
		return GormMysql()
	}
}

// MysqlTables
// @author: SliverHorn
// @function: MysqlTables
// @description: 注册数据库表专用
// @param: db *gorm.DB
func MysqlTables(db *gorm.DB) {
	err := db.AutoMigrate(
		system.SysConfig{},
		system.SysUser{},
		system.SysRole{},
		system.SysUserRole{},
		system.SysApi{},
		system.SysPermission{},
		system.SysRolePermission{},
		system.JwtBlacklist{},
		system.SysDict{},
		system.SysDictDetail{},
		system.SysLog{},
		system.SysDepartment{},
		system.SysDepartmentHeader{},
		system.SysRoleDepartment{},
		system.SysMessage{},
		system.SysDict{},
		system.SysDictDetail{},
		storage.SysUploadFile{},
		storage.ExaFile{},
		storage.ExaFileChunk{},
		storage.ExaSimpleUploader{},
		storage.ExaCustomer{},
		generator.SysAutoCodeHistory{},
		// Code generated by gin-myboot Begin; DO NOT EDIT.
		article.SysArticle{},
		// Code generated by gin-myboot End; DO NOT EDIT.
	)
	if err != nil {
		global.Logger.Error("register table failed", zap.Any("err", err))
		os.Exit(0)
	}
	global.Logger.Info("register table success")
}

// GormMysql
// @author: SliverHorn
// @function: GormMysql
// @description: 初始化Mysql数据库
// @return: *gorm.DB
func GormMysql() *gorm.DB {
	m := global.Config.Mysql
	if m.Dbname == "" {
		return nil
	}
	dsn := m.Username + ":" + m.Password + "@tcp(" + m.Path + ")/" + m.Dbname + "?" + m.Config
	mysqlConfig := mysql.Config{
		DSN:                       dsn,   // DSN data source name
		DefaultStringSize:         191,   // string 类型字段的默认长度
		DisableDatetimePrecision:  true,  // 禁用 datetime 精度，MySQL 5.6 之前的数据库不支持
		DontSupportRenameIndex:    true,  // 重命名索引时采用删除并新建的方式，MySQL 5.7 之前的数据库和 MariaDB 不支持重命名索引
		DontSupportRenameColumn:   true,  // 用 `change` 重命名列，MySQL 8 之前的数据库和 MariaDB 不支持重命名列
		SkipInitializeWithVersion: false, // 根据版本自动配置
	}
	if db, err := gorm.Open(mysql.New(mysqlConfig), gormConfig()); err != nil {
		//global.Logger.Error("MySQL启动异常", zap.Any("err", err))
		//os.Exit(0)
		//return nil
		return nil
	} else {
		sqlDB, _ := db.DB()
		sqlDB.SetMaxIdleConns(m.MaxIdleConns)
		sqlDB.SetMaxOpenConns(m.MaxOpenConns)
		return db
	}
}

// @author: SliverHorn
// @function: gormConfig
// @description: 根据配置决定是否开启日志
// @param: mod bool
// @return: *gorm.Config
func gormConfig() *gorm.Config {
	config := &gorm.Config{DisableForeignKeyConstraintWhenMigrating: true}
	switch global.Config.Mysql.LogMode {
	case "silent", "Silent":
		config.Logger = internal.Default.LogMode(logger.Silent)
	case "error", "Error":
		config.Logger = internal.Default.LogMode(logger.Error)
	case "warn", "Warn":
		config.Logger = internal.Default.LogMode(logger.Warn)
	case "info", "Info":
		config.Logger = internal.Default.LogMode(logger.Info)
	default:
		config.Logger = internal.Default.LogMode(logger.Info)
	}
	return config
}
